workflows:
  ios-maui-build:
    name: Build .NET MAUI iOS App
    environment:
      xcode: 15.2
      vars:
        DOTNET_VERSION: 8.0.203
    scripts:
      - name: Show .NET version
        script: dotnet --info
      - name: Build iOS App
        script: dotnet build MauiApp2.sln -f net8.0-ios -c Release
    artifacts:
      - "**/*.ipa"
