workflows:
  ios-maui:
    name: .NET MAUI iOS Build
    environment:
      xcode: latest
      vars:
        DOTNET_ROOT: /usr/local/share/dotnet
        PATH: /usr/local/share/dotnet:/opt/homebrew/bin:/usr/local/bin:$PATH
    scripts:
      - dotnet --info
      - dotnet workload restore
      - dotnet build MauiApp2.sln -c Release -f:net8.0-ios
    artifacts:
      - "**/bin/**/*.ipa"