workflows:
  ios-maui:
    name: MAUI Build for iOS (with Homebrew)
    environment:
      xcode: latest
    scripts:
      - echo "Installing .NET via Homebrew"
      - brew install --cask dotnet-sdk
      - export PATH="/usr/local/share/dotnet:$PATH"
      - dotnet --info
      - dotnet workload install maui
      - dotnet workload restore
      - dotnet build MauiApp2.sln -c Release -f:net8.0-ios
    artifacts:
      - "**/bin/**/*.ipa"