workflows:
  ios-maui-build:
    name: Build .NET MAUI for iOS
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: 8.0.204
    scripts:
      - echo "Installing .NET..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION
      - export PATH="$PATH:$HOME/.dotnet"
      - dotnet workload install maui
      - dotnet workload restore
      - dotnet build MauiApp2.sln -c Release -f:net8.0-ios
    artifacts:
      - "**/bin/**/*.ipa"